apiVersion: v1
kind: Pod
metadata:
  name: kuard
spec:
  containers:
  # to build local image, go to the kuard folder and use 
  # 1) docker build . -t kuard:local 
  # 2) docker save kuard > kuard.tar
  # 3) microk8s ctr image import kuard.tar

  - image: kuard:local
    name: kuard
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
